neddit/neddit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

neddit/website/urls.py
from django.urls import path, include

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('landing/', views.LandingView.as_view(), name='landing'),
    path('faq/', views.FaqView.as_view(), name='faq'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('n/', views.view_subnedditlist, name='subnedditlist'), 
    path('n/<str:sub_id>/', views.view_subneddit, name='subneddit'),
    path('n/<str:sub_id>/new/', views.view_newpost, name='newpost'),
    path('n/<str:sub_id>/<int:post_id>/', views.view_post, name='viewpost'),
    path('n/<str:sub_id>/<int:post_id>/<int:parent_comment_id>/',
            views.post_comment,
            name="postcomment"),
    path('n/<str:sub_id>/<int:post_id>/download/',
            views.post_downloadfile, name='postdownload'),
]

neddit/website/models.py
from django.db import models
from django.contrib.auth import get_user_model

from datetime import datetime


class Subneddit(models.Model):
    id = models.CharField(
        verbose_name="Course Code", max_length=8, primary_key=True)
    name = models.CharField(verbose_name="Course Name", max_length=100)
    subscribed = models.ManyToManyField(
        get_user_model(), related_name="Subscriber", blank=True)
    admin = models.ManyToManyField(
        get_user_model(), related_name="Admin")
    sidebar = models.TextField(verbose_name="Sidebar Text", blank=True)

    def __str__(self):
        return self.id + ' (' + self.name + ')'


class Post(models.Model):
    def makepath(instance, filename):
        now = datetime.now()
        # TODO: Find a better way to address concurrency issue here
        return '{0}/{1}/{2}/{3}'.format(
            instance.subneddit.id,
            instance.author.username,
            now.strftime("%Y-%m-%d-%H-%M-%S"),
            filename)

    subneddit = models.ForeignKey(Subneddit, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    submitDate = models.DateTimeField()
    isTextPost = models.BooleanField()
    content = models.TextField()
    author = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE)
    notefile = models.FileField(upload_to=makepath, blank=True, null=True)

    def __str__(self):
        return self.title + '-' + self.subneddit.id + '-' + self.author.username


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parentComment = models.ForeignKey(
        'Comment', on_delete=models.CASCADE, blank=True, null=True)
    content = models.TextField()
    submitDate = models.DateTimeField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return ('Comment on ' + self.post.title + ' by ' + self.author.username
            + ' (' + str(self.submitDate) + ')')


class PostVotes(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    voteVal = models.IntegerField()

    def __str__(self):
        return self.post.title + '-' + self.user.username + '-' + str(self.voteVal)


class CommentVotes(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    voteVal = models.IntegerField()

    def __str__(self):
        return str(self.comment) + '-' + str(self.voteVal)

neddit/website/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput())


class PostForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200)
    content = forms.CharField(
        label="Content", widget=forms.Textarea, required=False)
    file = forms.FileField(label="Upload Notes", required=False)


class CommentForm(forms.Form):
    comment = forms.CharField(label="Make a comment")

neddit/website/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.http import HttpResponseNotFound, HttpResponseServerError
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from .forms import CommentForm, LoginForm, PostForm
from .models import Comment, Post, Subneddit
from .utils import create_comment, create_post, get_comments

import os


class BaseView(generic.TemplateView):
    template_name = 'website/base.html'


class LandingView(BaseView):
    template_name = 'website/landing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = LoginForm()
        return context


class IndexView(BaseView):
    template_name = 'website/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        return context


class FaqView(BaseView):
    template_name = 'website/faq.html'


def view_subnedditlist(request):
    context = { 'subneddits': Subneddit.objects.all() }
    return render(request, 'website/subnedditlist.html', context)


def view_subneddit(request, sub_id):
    sub_id = sub_id.upper() # subneddit code is always uppercase
    subneddit_obj = Subneddit.objects.get(id=sub_id)
    if not subneddit_obj:
        return HttpResponseNotFound()

    posts = subneddit_obj.post_set.all() # get all posts in this subneddit
    context = {
        'subneddit': subneddit_obj,
        'sidebar': "",
        'posts': posts
    }
    return render(request, 'website/subneddit_posts.html', context)


def view_newpost(request, sub_id):
    sub_id = sub_id.upper()
    subneddit_obj = Subneddit.objects.get(id=sub_id)
    if not subneddit_obj:
        return HttpResponseNotFound()

    context = {
        'subneddit': subneddit_obj,
        'sidebar': "",
        'form': PostForm(),
    }
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        title = request.POST['title']
        author = request.user
        content = request.POST['content']

        try:
            file = request.FILES['file']
        except Exception as e:
            file = None
        isTextPost = True if file is not None else False

        post_obj = create_post(sub_id, title, author, content, file, isTextPost)
        if post_obj is not None:
            return HttpResponseRedirect(
                reverse('website:viewpost', args=(sub_id, post_obj.id,)))
        return HttpResponseServerError()

    return render(request, 'website/subneddit_newpost.html', context)


def view_post(request, sub_id, post_id):
    sub_id = sub_id.upper()
    subneddit_obj = Subneddit.objects.get(id=sub_id)
    if not subneddit_obj:
        return HttpResponseNotFound()

    post_obj = Post.objects.get(id=post_id)
    if not post_obj:
        return HttpResponseNotFound()

    comments = get_comments(post_obj)
    context = {
        'subneddit': subneddit_obj,
        'sidebar': "",
        'post': post_obj,
        'comments': comments,
        'form': CommentForm()
    }
    return render(request, 'website/subneddit_viewpost.html', context)


def post_comment(request, sub_id, post_id, parent_comment_id):
    if (request.method != "POST"
            or request.POST['comment'] is None
            or len(request.POST['comment']) == 0):
        # show post page if not post request, or no text entered
        return view_post(request, sub_id, post_id)
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    sub_id = sub_id.upper()
    subneddit_obj = Subneddit.objects.get(id=sub_id)
    if not subneddit_obj:
        return HttpResponseNotFound()
    post_obj = Post.objects.get(id=post_id)
    if not post_obj:
        return HttpResponseNotFound()

    parent_comment_obj = None
    if parent_comment_id > 0:  # if <= 0, no parent comment
        parent_comment_obj = Comment.objects.get(id=parent_comment_id)
        if not parent_comment_obj:
            return HttpResponseNotFound()

    comment_obj = create_comment(
            post_obj, parent_comment_obj, request.POST['comment'], request.user)

    if comment_obj is not None:
        return HttpResponseRedirect(
            reverse('website:viewpost', args=(sub_id, post_obj.id,)))
    return HttpResponseServerError()

def post_downloadfile(request, sub_id, post_id):
    sub_id = sub_id.upper()
    subneddit_obj = Subneddit.objects.get(id=sub_id)
    if not subneddit_obj:
        return HttpResponseNotFound()

    post_obj = Post.objects.get(id=post_id)
    if not post_obj or post_obj.notefile is None:
        return HttpResponseNotFound()
    filename = os.path.basename(post_obj.notefile.url)
    response = HttpResponse(post_obj.notefile.file, content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename=%s' % filename
    return response

neddit/website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en-au">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'website/styles.css' %}" />
  <title>{% block title %}Neddit{% endblock %}</title>
</head>

<body>
  <div id="navbar">
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
      <a class="navbar-brand" href="{% url 'website:index' %}">Neddit</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:subnedditlist' %}">Find Subneddits</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'website:faq' %}">FAQ</a>
          </li>
          {% if user.is_superuser %} <!-- only displayed if user is logged in as superuser -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin (superuser only)</a>
          </li>
          {% endif %}
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search for posts..." aria-label="Search">
              <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a href="{% url 'website:logout' %}">
                <button class="btn btn-outline-light mx-2">Logout</button></a>
            {% else %}
              <a href="{% url 'website:login' %}">
                <button class="btn btn-outline-light mx-2">Login</button></a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    {% endblock %}
  </div>

  <div id="content">
    {% block alert %}{% endblock %}
    {% block content %}{% endblock %}
  </div>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <p style="font-size: 14px;"><b>Disclaimer:</b> Neddit is not an actual website or service. This is a
          course assignment project for INFS2608, Sem. 1 2018 at UNSW. Project
          by Group Fourteen</p>
      </div>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>

neddit/website/templates/website/faq.html
{% extends "website/base.html" %}
{% block content %}
<div class="container">
  <div class="container card my-2">
    <div class="card-body">
      <h1>FAQ</h1>
    </div>
  </div>
  <div class="container card my-2">
    <div class="card-body">
      <h4>What is Neddit and how do I use it?</h4>
      <p>
        Neddit is an online community for UNSW students to share notes, collaborate,
        ask questions, discuss courses and support each other in each course.
        It is a crowdsourcing platform where students can upload their own notes
        and provide helpful advice for others. Courses are split by sections known
        as "subneddits". Users can post notes and create discussions in each
        subneddit. Each post can be voted up if a user feels it is helpful, and
        voted down otherwise. These are called "upnote" and "downnote" respectively.
        The higher amount of votes a post has, the more visibility it gets.
      </p>

      <h4>How do I report abuse or plagiarised work?</h4>
      <p>
        Each subneddit will have admins in change of monitoring all the posts.
        Neddit has a strict policy on plagiarism and all offences should be
        reported to the moderators of the relevant subreddit, found in the sidebar.
      </p>

      <h4>Can I advertise my private services (e.g. tutoring, textbook selling)
      on Neddit?</h4>
      <p>
        No. Neddit is primarily focused on online collaboration and notesharing.
        We do not facilitate the exchange of goods or services. For such activities,
        please seek other available platforms online.
      </p>
      <p><i>
        For further support, contact the course subneddit's moderator or
        email us at <a href="mailto:support@neddit.com.au">support@neddit.com.au</a>.
      </i></p>
    </div>
  </div>
</div>
{% endblock %}

neddit/website/templates/website/index.html
{% extends "website/base.html" %}
{% block content %}
<div class="container">
  <div class="card my-2">
    <div class="card-body">
      {% if user.is_authenticated %}
      <h2>Welcome back {{ user.username }}!</h2>
      {% else %}
      <h2>Welcome to Neddit!</h2>
      {% endif %}
    </div>
  </div>
  {% if posts %}
    {% for p in posts %}
    <div class="card my-2">
      <div class="card-body">
        <a href="{% url 'website:viewpost' sub_id=p.subneddit.id post_id=p.id %}">
          <h5 class="card-title">{{ p.title }}</h5>
        </a>
        <p>Posted by <a href="#">{{ p.author.username }}</a> on {{ p.submitDate }}
          <br/>
          <a href="{% url 'website:subneddit' sub_id=p.subneddit.id %}">
            <span class="text-muted">n/{{ p.subneddit.id }}</span>
          </a>
        </p>
      </div>
    </div>
    {% endfor %}
  {% else %}
    <div class="card my-2">
      <div class="card-body">
        <p>No posts yet :(</p>
      </div>
    </div>
  {% endif %}
</div>

{% endblock %}

neddit/website/templates/website/landing.html
{% extends "website/base.html" %}
{% load bootstrap4 %}
{% block navbar %}{% endblock %} <!-- remove the navbar -->
{% block content %}
<div class="container-fluid">
  <!-- Page Content -->
    <section>
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h1 class="mt-5 title">Neddit.</h1>
            <p>A web application for UNSW communities, we empower students and
            staff with the ability to share and upload course notes and discuss courses.
            Student run and free to use.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4">
          {% if user.is_authenticated %}
            <a href="{% url 'website:index' %}">
              <button class="btn btn-outline-light">Continue to Neddit</button></a>
          {% else %}
            <form method="POST" action="{% url 'website:login' %}">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% buttons %}
                <button class="btn btn-outline-light" type="submit">Login</button>
              {% endbuttons %}
            </form>
          {% endif %}
          </div>
        </div>
      <div class="container">

        </div>
      </div>
    </section>
</div>

<!-- TODO: Put this in an actual CSS file -->
<style>
body {
  background: rgba(99, 216, 149, 1);
  color: white;
}

h1 {
  font-size: 8rem;
}

p {
  font-size: 1.5rem;
}
</style>
{% endblock %}

neddit/website/templates/website/post_comment.html
{% load bootstrap4 %}
{% if comments %}
  {% for c in comments %}
    <div class="card my-2">
      <div class="card-body">
        <p>{{ c.comment.content }}</p>
        <p class="text-muted">
          Posted by {{ c.comment.author }} on {{ c.comment.submitDate }}
        </p>

        {% if user.is_authenticated %}
          <form method="POST" class="form-inline"
              action="{% url 'website:postcomment' sub_id=subneddit.id post_id=post.id parent_comment_id=c.comment.id %}">
            {% csrf_token %}

            {% bootstrap_form form layout='inline' %}
            {% bootstrap_button "Submit" button_type="submit" button_class="btn-outline-dark" %}
          </form>
        {% endif %}
        {% include 'website/post_comment.html' with comments=c.children %}
      </div>
    </div>
  {% endfor %}
{% endif %}

neddit/website/templates/website/subneddit_base.html
{% extends "website/base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card my-2">
        <div class="card-body">
          <h4 class="display-4">{{ subneddit.name }}</h4>
          <h4><a href="{% url 'website:subneddit' sub_id=subneddit.id %}">
            n/{{ subneddit.id }}
          </a></h4>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      {% block subneddit_content %}{% endblock %}
    </div>
    <div class="col-sm-4"> <!-- Sidebar -->
      <div class="card my-2">
        <div class="card-body">
          <a href="{% url 'website:newpost' sub_id=subneddit.id %}" class="btn btn-primary btn-block">
            Create New Post</a>
            <br/>
          <h4>Sidebar</h4>
          {% if subneddit.sidebar %}
            {{ subneddit.sidebar|linebreaks }}
          {% else %}
            Nothing to see here.
          {% endif %}
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

neddit/website/templates/website/subneddit_newpost.html
{% extends "website/subneddit_base.html" %}
{% load bootstrap4 %}
{% block subneddit_content %}
<div class="card my-2">
  <div class="card-body">
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button class="btn btn-outline-primary btn-block" type="submit">Submit</button>
      {% endbuttons %}
    </form>
    {% else %}
    <p>You need to be logged in to make a post.</p>
    {% endif %}
  </div>
</div>

{% endblock %}

neddit/website/templates/website/subneddit_posts.html
{% extends "website/subneddit_base.html" %}
{% block subneddit_content %}

{% if posts %}
  {% for post in posts %}
  <div class="card my-2">
      <div class="card-body">
        <a href="{% url 'website:viewpost' sub_id=subneddit.id post_id=post.id %}">
          <h5 class="card-title">{{ post.title }}</h5>
        </a>
        <p>Posted by <a href="#">{{ post.author.username }}</a> on {{ post.submitDate }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
{% else %}
<div class="card my-2">
  <div class="card-body">
    <p>No posts in this subneddit :(</p>
  </div>
</div>
{% endif %}

{% endblock %}

neddit/website/templates/website/subneddit_viewpost.html
{% extends "website/subneddit_base.html" %}
{% load bootstrap4 %}
{% block subneddit_content %}
<div class="card my-2 border-dark">
  <h5 class="card-header">{{ post.title }}</h5>
  <div class="card-body">
    {% if post.notefile %}
      <a class="btn btn-primary"
          href="{% url 'website:postdownload' sub_id=subneddit.id post_id=post.id %}">
          Download
      </a>
    {% endif %}
    <p class="card-text">{{ post.content|linebreaks }}</p>
  </div>
  <div class="card-footer text-muted">
    Posted by {{ post.author }} on {{ post.submitDate }}
  </div>
</div>

{% if user.is_authenticated %}
  <br/>
  <h5>Reply to this post</h5>
  <form method="POST"
      action="{% url 'website:postcomment' sub_id=subneddit.id post_id=post.id parent_comment_id=0 %}">
    {% csrf_token %}

    {% bootstrap_form form layout='inline' %}
    {% bootstrap_button "Submit" button_type="submit" button_class="btn-outline-dark" %}
  </form>
{% endif %}

<hr />
<h4>Comments</h4>
{% if comments %}
  {% include 'website/post_comment.html' with comments=comments form=form %}
{% else %}
  <p>Nobody has commented yet :(</p>
{% endif %}

{% endblock %}

neddit/website/templates/website/subnedditlist.html
{% extends "website/base.html" %}
{% block content %}
<div class="container">
  {% if subneddits %}
    <div class="card my-2">
      <div class="card-body">
        <h2>Find Subneddits</h2>
      </div>
    </div>
    {% for s in subneddits %}
    <div class="card my-2">
      <div class="card-body">
        <a href="{% url 'website:subneddit' sub_id=s.id %}">
          <h5 class="card-title">{{ s.id }}</h5>
        </a>
        <p>{{ s.name }}</p>
      </div>
    </div>
    {% endfor %}
  {% else %}
    <div class="card my-2">
      <div class="card-body">
        <p>No subneddits available yet.</p>
      </div>
    </div>
  {% endif %}
</div>

{% endblock %}